inherit_from: "configs/rgbd/bonn/base_config.yaml"

Dataset:
  dataset_path: "datasets/tum/rgbd_bonn_placing_nonobstructing_box3"
  bound: [[-8.0, -8.5, -7.0],[8.5, 8.5, 8.0]]  # Deformation Net aabb
  #node_downsample_init: 32
  Calibration:
    fx: 542.822841
    fy: 542.576870
    cx: 315.593520
    cy: 237.756098
    k1: 0.039903
    k2: -0.099343
    p1: -0.00073
    p2: -0.000144
    k3: 0.0
    distorted: True
    width: 640
    height: 480
    depth_scale: 5000.0
    
Training:
  single_thread: True
  #mapping_itr_num: 150
  dystart: 348