inherit_from: "configs/rgbd/cofusion/base_config.yaml"

Dataset:
  dataset_path: "datasets/cofusion/room4-full"
  Calibration:
    fx: 360
    fy: 360
    cx: 320
    cy: 240
    k1: 0.0
    k2: 0.0
    p1: 0.0
    p2: 0.0
    k3: 0.0
    distorted: False
    width: 640
    height: 480
    depth_scale: 1.
    
Training:
  single_thread: True
  mapping_itr_num: 150   # 150